fix: add lastActiveLogIndex
highlight/highlight pull request #6441
Opened 2023-08-27 10:42 UTC by jainpawan21

## Summary
1. Add `lastActiveLogIndex` and active styling

/claim #4872 
closes #4872 

## How did you test this change?

## Are there any deployment considerations?

2023-08-29 16:39 UTC, et requested changes
This is looking great. I did notice that we already have logic to track the current log index (see `foundIndex`). I think what you have here (using `findLastActiveEventIndex`) makes a lot of sense but it would be great to drop the old logic.

Can we try the following:

* Remove the `foundIndex` code
* Remove the `useEffect` with the comment `// Logic for scrolling to current entry.`
* Update references to `foundIndex` to point to `lastActiveLogIndex`
* Update the `current` prop to `<MessageRow />` to be `_index == lastActiveLogIndex`
* Add a new prop to `<MesageRow />` called `selectedLog` which should work like `selectedError` does on the errors tab ([source](https://github.com/highlight/highlight/blob/1a93b44d8aadc3929aff4fca7d81e098211b33a0/frontend/src/pages/Player/Toolbar/DevToolsWindowV2/ErrorsPage/ErrorsPage.tsx#L136-L180)).

2023-09-12 22:57 UTC, Vadman97 commented on frontend/src/pages/Player/Toolbar/DevToolsWindowV2/ConsolePage/ConsolePage.tsx
> +	}, [messageNodes, sessionMetadata.startTime, time])
seems like this change to the deps of the useEffect below means that the `Go to` button on logs no longer works

could you see why it's not working? this is a regression from `main` as the button works fine there
<img width="1133" alt="Screenshot 2023-09-12 at 3 57 03 PM" src="https://github.com/highlight/highlight/assets/1351531/d35cb37d-e76e-44d1-a761-219e1bc053f1">

2023-09-29 19:12 UTC, Vadman97 commented
how's this going @jainpawan21 ?

2023-10-13 20:26 UTC, rishi-raj-jain commented
@jainpawan21 let me know if I can continue this and we can split.

2023-10-20 20:41 UTC, jainpawan21 commented
> @jainpawan21 let me know if I can continue this and we can split.

Hi @rishi-raj-jain, Sure you can continue this.

2023-10-20 20:42 UTC, jainpawan21 commented
> how's this going @jainpawan21 ?

Sorry Vadim for late response.
I have been caught in some work and getting very less time.

Let @rishi-raj-jain continue this 🙂

2023-11-07 07:40 UTC, rishi-raj-jain commented
@Vadman97 are you fine with me working on this?

2023-11-29 06:00 UTC, Vadman97 commented
yes, please go ahead @rishi-raj-jain

2023-11-29 06:35 UTC, rishi-raj-jain commented
Thanks, on it!

2023-12-09 18:38 UTC, rishi-raj-jain commented
@vadman97  my mac broke :/

2024-05-20 19:04 UTC, closed without merging