fix: Improve console errors empty state
highlight/highlight pull request #6454
Opened 2023-08-28 20:12 UTC by rishi-raj-jain

fix: #5923
/claim #5923

2023-08-28 20:30 UTC, rishi-raj-jain commented
@mayberryzane @Vadman97

This is ready for review now. Should be exactly like the design.

2023-08-28 20:38 UTC, Vadman97 requested changes
the filter state should be updated per the ticket
<img width="470" alt="Screenshot 2023-08-28 at 1 37 30 PM" src="https://github.com/highlight/highlight/assets/1351531/fdc3e91b-ba8b-48b2-bf60-1b9b88c9f995">

also, in the design, the text wraps rather than staying as 1 line
![image](https://github.com/highlight/highlight/assets/1351531/543d1a14-41a5-47e9-a387-c170c66f176e)

2023-08-28 20:48 UTC, rishi-raj-jain commented
@Vadman97 

Can you help me where I can see that view and reproduce that?

In local, I had to replace one of the random components to be able to get the view of EmptyDevToolsCallout component, and how it's rendered.

2023-08-29 05:44 UTC, rishi-raj-jain commented
@Vadman97

Can you help me where I can see that view and reproduce that?

In local, I had to replace one of the random components to be able to get the view of EmptyDevToolsCallout component, and how it's rendered.

2023-08-29 15:32 UTC, rishi-raj-jain commented
@Vadman97 @ccschmitz

Can you help me where I can see that view and reproduce that?

In local, I had to replace one of the random components to be able to get the view of EmptyDevToolsCallout component, and how it's rendered.

2023-08-31 06:44 UTC, Vadman97 commented
@rishi-raj-jain you can look at the [following session here](https://preview.highlight.io/1/sessions/t1j4yjT5cYy0ogLdvFQFJiw2hwQJ?page=1&query=and%7C%7Ccustom_processed%2Cis%2Ctrue%7C%7Ccustom_created_at%2Cbetween_date%2C2023-08-01T06%3A43%3A12.035Z_2023-08-31T06%3A43%3A12.035Z&%7Er_preview=%7B%22action%22%3A%22start%22%2C%22mode%22%3A%22production%22%2C%22region%22%3A%22sjc%22%2C%22variantId%22%3A%2201H8YXFM4JHBYSDCN7Z5BRX2MA%22%2C%22variantData%22%3A%22%7B%5C%22type%5C%22%3A%5C%22branch%5C%22%2C%5C%22branch%5C%22%3A%5C%22fix-info%5C%22%2C%5C%22forkSpecifier%5C%22%3A%5C%22rishi-raj-jain%2Fhighlight%5C%22%2C%5C%22githubOwnerName%5C%22%3A%5C%22highlight%5C%22%2C%5C%22githubRepositoryName%5C%22%3A%5C%22highlight%5C%22%7D%22%7D) 

<img width="1663" alt="Screenshot 2023-08-30 at 11 44 34 PM" src="https://github.com/highlight/highlight/assets/1351531/58203cd2-45e1-47fa-978e-0175069772d5">

2023-08-31 15:40 UTC, rishi-raj-jain commented
What I see:

<img width="1512" alt="Screenshot 2023-08-31 at 9 10 09 PM" src="https://github.com/highlight/highlight/assets/46300090/c554222e-da49-43b3-91d8-345afd4f034b">

2023-08-31 19:07 UTC, Vadman97 commented
@rishi-raj-jain you may have to view the session in an incognito window (not logged in) to view it publicly

2023-09-01 15:58 UTC, rishi-raj-jain commented
@Vadman97 what I see in incognito

<img width="1512" alt="Screenshot 2023-09-01 at 9 27 36 PM" src="https://github.com/highlight/highlight/assets/46300090/1a6f4ea6-c308-4c21-bb31-93126333fa80">

2023-09-01 18:26 UTC, Vadman97 commented
yup, that's correct. now click the terminal icon in the bottom right to open up the console 
<img width="313" alt="image" src="https://github.com/highlight/highlight/assets/1351531/a108975d-27cf-41c7-a1bf-7382b50a6c85">

2023-09-02 09:57 UTC, rishi-raj-jain commented
<img width="1512" alt="Screenshot 2023-09-02 at 3 27 08 PM" src="https://github.com/highlight/highlight/assets/46300090/71646b31-9567-4fc8-b0bb-24cbad074c00">

2023-09-02 10:34 UTC, rishi-raj-jain commented
@Vadman97 I think for this to be deployed for a preview, needs your authorization

2023-09-02 18:42 UTC, rishi-raj-jain commented
@Vadman97 I think for this to be deployed for a preview, needs your authorization

2023-09-04 22:21 UTC, rishi-raj-jain commented
@Vadman97 I think for this to be deployed for a preview, needs your authorization

2023-09-05 07:23 UTC, rishi-raj-jain commented
@Vadman97 I think for this to be deployed for a preview, needs your authorization

2023-09-05 17:33 UTC, Vadman97 reviewed
getting there! some feedback from the preview

2023-09-05 17:33 UTC, Vadman97 commented on frontend/src/pages/Player/Toolbar/DevToolsWindowV2/EmptyDevToolsCallout/EmptyDevToolsCallout.tsx
> +						? `Only see one app version?`
```suggestion
						? `Can't find what you're looking for?`
```

2023-09-05 17:33 UTC, Vadman97 commented on frontend/src/pages/Player/Toolbar/DevToolsWindowV2/EmptyDevToolsCallout/EmptyDevToolsCallout.tsx
> +							entry. Try again with another retry!
```suggestion
							entry. Try search for something else!
```

2023-09-05 17:33 UTC, Vadman97 commented on frontend/src/pages/Player/Toolbar/DevToolsWindowV2/EmptyDevToolsCallout/EmptyDevToolsCallout.tsx
> +			}}
the callout is not centered

![Screenshot from 2023-09-05 10-30-39](https://github.com/highlight/highlight/assets/1351531/75a7c4c3-1130-4553-a781-9713ba576ea8)

![Screenshot from 2023-09-05 10-29-22](https://github.com/highlight/highlight/assets/1351531/b94732b2-7738-48bf-8089-52f82c05bac2)

2023-09-06 10:01 UTC, rishi-raj-jain commented
@Vadman97 This is ready for your review.

2023-09-06 18:19 UTC, Vadman97 commented
@rishi-raj-jain this is failing the build; please run `yarn reflame-build` and commit the updated files

2023-09-06 18:54 UTC, rishi-raj-jain commented
@Vadman97 Done, somehow it wasn't committed.

2023-09-06 19:58 UTC, Vadman97 commented on frontend/src/pages/Player/Toolbar/DevToolsWindowV2/ConsolePage/style.css.ts
> +	justifyContent: 'center',
this still isn't centered

![Screenshot from 2023-09-05 22-33-31](https://github.com/highlight/highlight/assets/1351531/075de6fd-ea5f-4b99-82b9-ace16d5c694f)

![image](https://github.com/highlight/highlight/assets/1351531/e042d7f6-28f4-4ec0-896b-a6ccac803aea)

2023-09-06 19:58 UTC, Vadman97 commented on frontend/src/pages/Player/Toolbar/DevToolsWindowV2/ConsolePage/style.css.ts
> +	justifyContent: 'center',
this still isn't centered

![Screenshot from 2023-09-05 22-33-31](https://github.com/highlight/highlight/assets/1351531/075de6fd-ea5f-4b99-82b9-ace16d5c694f)

![image](https://github.com/highlight/highlight/assets/1351531/e042d7f6-28f4-4ec0-896b-a6ccac803aea)

2023-09-06 19:58 UTC, Vadman97 requested changes
looks like the box still isn't centered

2023-09-07 02:50 UTC, rishi-raj-jain commented
I just wish there was a way for me to test all of this locally!

But anyways, I seem to have applied the css at the wrong place, shall be on the callout now.

Can you deploy and check?

2023-09-07 05:54 UTC, rishi-raj-jain commented
I just wish there was a way for me to test all of this locally!

But anyways, I seem to have applied the css at the wrong place, shall be on the callout now.

Can you deploy and check?

2023-09-07 17:21 UTC, Vadman97 requested changes
nice! this is centered now, but there is no margin around the callout box as the design has.

as for testing locally, you can easily spin up the stack as per our docs and view the frontend locally. reach out on discord if you have issues with that
https://www.highlight.io/docs/getting-started/self-host/dev-deployment-guide

2023-09-08 09:11 UTC, rishi-raj-jain commented
I did do all of the setup, but the issue is I'm not able to load the session link in which the error is visible.

2023-09-08 09:13 UTC, rishi-raj-jain commented
> but there is no margin around the callout box as the design has.

What margin are you referring to? I see the design of the callout exactly like the design has.

2023-09-12 04:06 UTC, Vadman97 commented
some errors now @rishi-raj-jain 

<img width="1197" alt="Screenshot 2023-09-11 at 9 05 52 PM" src="https://github.com/highlight/highlight/assets/1351531/f3857828-3ca3-41e7-934c-63b05ee1b708">

2023-09-12 04:07 UTC, Vadman97 approved these changes
preview is looking good now!
<img width="1155" alt="Screenshot 2023-09-11 at 9 07 16 PM" src="https://github.com/highlight/highlight/assets/1351531/de42d094-e7ca-4d3d-b60c-d4ba17a21ad4">

2023-09-12 14:53 UTC, rishi-raj-jain commented
That's awesome!

![](https://media.giphy.com/media/G1vplGMypxBcp7kx32/giphy.gif)

2023-09-12 20:20 UTC, merged