add backendUrl in setup docs for frontend SDKs
highlight/highlight pull request #6489
Opened 2023-09-01 08:23 UTC by KaranJagtiani

## Summary

This PR addresses issue #5742 with the goal of streamlining the setup process for users deploying Highlight on their own infrastructure or local machine. Specifically, the PR auto-populates the `backendUrl` attribute in the SDK initialization code snippets across all frontend SDKs supported by Highlight.

## How did you test this change?

Frontend

- Local testing involved setting up various types of frontend applications supported by Highlight. Subsequently, I followed the initialization steps for the Highlight SDK, verifying that the `backendUrl` attribute was correctly auto-populated in each case.

Example - for Next.js:
![Screenshot 2023-09-01 at 1 52 11 PM](https://github.com/highlight/highlight/assets/39665675/d6eedca2-5fed-41a2-8e25-7154564368ff)

## Are there any deployment considerations?

- No database migrations or data backfilling are required for this change.

2023-09-01 08:25 UTC, KaranJagtiani commented
Note: This implementation will auto-populate the `backendUrl` attribute not only for self-hosted instances but also for the https://app.highlight.io/ environment. As far as I could tell, limiting this feature strictly to self-hosted stacks poses challenges, particularly given the current mechanism for populating the `<YOUR_PROJECT_ID>` from the [highlight.io](http://highlight.io/) project.

Please let me know if there is a better way to do this. cc: @jay-khatri @Vadman97  @ccschmitz

2023-09-01 08:26 UTC, KaranJagtiani commented
Additionally, I encountered an issue when setting up a Gatsby app: I wasn't able to add the `backendUrl` attribute as I did with other frontend frameworks. Is this a limitation of the Gatsby plugin, or might I be overlooking something?

2023-09-01 15:52 UTC, Vadman97 requested changes
> 

Hey @KaranJagtiani - `backendUrl` only makes sense for self hosted environments. This setting routes data to a custom highlight backend url, and by default, we want folks using the cloud backend (pub.highlight.io). Your implementation will set `backendUrl: "https://pub.highlight.io"` for cloud usage of the SDKs, but this is not necessary (will just confuse folks) since that's already the default value.

Regarding `gatsby` - that is likely correct as we don't support that setting on that SDK yet.

2023-09-03 00:57 UTC, KaranJagtiani commented on highlight.io/components/QuickstartContent/frontend/angular.tsx
> +    backendUrl: '<YOUR_BACKEND_URL>',
@Vadman97, thanks for your response, I understand the concern.

The problem that I faced while trying to implement the approach that you have mentioned is that all the quick start guides are part of the `highlight.io` package, and the `PUBLIC_GRAPH_URI` env variable is not available over there. As far as I know, the env variables and core logic is part of the `frontend` package and that's how `<YOUR_PROJECT_ID>` is currently being populated.

How would you suggest that I tackle this problem?

2023-09-04 17:29 UTC, KaranJagtiani commented
@Vadman97, thanks for your response, I understand the concern.

The problem that I faced while trying to implement the approach that you have mentioned is that all the quick start guides are part of the highlight.io package, and the PUBLIC_GRAPH_URI env variable is not available over there. As far as I know, the env variables and core logic is part of the frontend package and that's how <YOUR_PROJECT_ID> is currently being populated.

How would you suggest that I tackle this problem?

2023-09-12 20:13 UTC, Vadman97 commented
> lement the approach that you have mentioned is that all the quick start guides are part of the highlight.io package, and the PUBLIC_GRAPH_URI env variable is not available over there. As far as I know, the env variables and core logic is part of the fron

https://github.com/highlight/highlight/blob/3c141cc3263a8180e2e770d7d69369f16d675c22/frontend/src/pages/Setup/SetupRouter/SetupRouter.tsx#L73

could you extend this backend request to return the public graph uri on self-hosted instances (based on util/env.go) and then inject that into the configs where applicable?

2023-09-13 17:48 UTC, KaranJagtiani commented
@Vadman97 I may not have been able to explain the problem to you before. I'll try to explain with an example. Within the actual code snippets, there is no way to check whether we are on https://pub.highlight.io or not. So the problem was how would we check if we want the `backendUrl: '<YOUR_BACKEND_URL>',` line to present in let's say the Angular code snippet:

```
const angularInitCodeSnippet = `// app.module.ts
    import { NgModule } from '@angular/core';
...

import { H } from 'highlight.run';

H.init('<YOUR_PROJECT_ID>', {
    backendUrl: '<YOUR_BACKEND_URL>', // This entire line shouldn't be there on https://pub.highlight.io
    environment: 'production',
    version: 'commit:abcdefg12345',
	networkRecording: {
		enabled: true,
		recordHeadersAndBody: true,
        urlBlocklist: [
            // insert full or partial urls that you don't want to record here
			// Out of the box, Highlight will not record these URLs (they can be safely removed):
			"https://www.googleapis.com/identitytoolkit",
			"https://securetoken.googleapis.com",
        ],
	},
});

@NgModule({
    ...
})
export class AppModule { }
`
```

Next.js and Remix code snippets have different syntax than the other frameworks.

To tackle this problem, this is what I came up with.

There would be a `replacements` array containing the regular expressions of what needs to be replaced. By default, this would be the contents of the array:

```
const replacements = [
	['<YOUR_PROJECT_ID>', projectVerboseId],
	['<YOUR_BACKEND_URL>', backendUrl],
]
```

If we are on the cloud version of Highlight, then add a few more regular expressions based on the different frameworks:

```
if (backendUrl === 'https://pub.highlight.io') {
	// Remove last element since we need to remove the entire line
	replacements.pop()

	// For Angular, Vue, SvelteKit, React, HTML/JS
	replacements.push([
		"[\r\n]+[ \t]*backendUrl: '<YOUR_BACKEND_URL>',",
		'',
	])

	// For Next
	replacements.push([
		"[\r\n]+[ \t]*backendUrl={'<YOUR_BACKEND_URL>'}",
		'',
	])

	// For Remix
	replacements.push([
		'[\r\n]+[ \t]*HIGHLIGHT_BACKEND_URL: process.env.HIGHLIGHT_BACKEND_URL,',
		'',
	])
	replacements.push([
		'[\r\n]+[ \t]*backendUrl={ENV.HIGHLIGHT_BACKEND_URL}',
		'',
	])
}
```

This results in:

### For Next.js:
| Without Backend URL               | With Backend URL               |
| ---------------------- | ---------------------- |
| ![Next without Backend URL](https://github.com/highlight/highlight/assets/39665675/52651658-acc5-43c9-a31f-19b31359c5db) | ![Next with Backend URL](https://github.com/highlight/highlight/assets/39665675/43230798-e5de-4db7-930b-9b69787b763d) |

### For Remix:
| Without Backend URL               | With Backend URL               |
| ---------------------- | ---------------------- |
| ![Remix without Backend URL](https://github.com/highlight/highlight/assets/39665675/6a809aad-515f-4a84-9750-a9d99f7d207e) | ![Remix with Backend URL](https://github.com/highlight/highlight/assets/39665675/49521576-091e-41bd-b275-474a25e47398) |

### For rest of the frameworks (Angular, Vue, SvelteKit, React, HTML/JS)
| Without Backend URL               | With Backend URL               |
| ---------------------- | ---------------------- |
| ![Angular without Backend URL](https://github.com/highlight/highlight/assets/39665675/082d4906-838d-488b-ba3e-54cff4a66b66) | ![Angular with Backend URL](https://github.com/highlight/highlight/assets/39665675/9fd043a7-cfcf-4e3a-8553-c0c7f6a3e7fa) |

2023-11-20 01:47 UTC, closed without merging