Update Next Titles for Algolia indexing
highlight/highlight pull request #7066
Opened 2023-11-02 19:39 UTC by jay-khatri

## Summary

## How did you test this change?

## Are there any deployment considerations?

## Does this work require review from our design team?

2023-11-02 19:43 UTC, deltaepsilon requested changes

2023-11-02 19:43 UTC, deltaepsilon commented on docs-content/getting-started/3_client-sdk/2_nextjs.md
> +title: Next.js Quick-start
```suggestion
title: Next.js Quick Start
```

2023-11-02 19:43 UTC, deltaepsilon commented on docs-content/getting-started/3_client-sdk/2_nextjs.md
> +heading: Next.js Quick-start
```suggestion
heading: Next.js Quick Start
```

2023-11-02 19:43 UTC, deltaepsilon commented on go.work.sum
> +github.com/goware/emailproviders v0.0.0-20200728124719-451ef785cf29/go.mod h1:2FoXdMtWJEKk3zBo2S5eaduD5Bh/5PIYwSlV66E1XMs=
`git reset` this file and run `git submodule update --recursive` to reset the `opentelemetry-sdk-workers` submodule.

2023-11-02 19:44 UTC, deltaepsilon commented on docs-content/getting-started/3_client-sdk/2_nextjs.md
> +title: Next.js Quick-start
These `Quick-start` to `Quick Start` edits are optional, but I wanted to make sure that the other comment was addressed, hence the "requested changes".

2023-11-10 02:56 UTC, Vadman97 approved these changes

2023-11-10 04:05 UTC, merged