feat: Microsoft Teams Integration
highlight/highlight pull request #7150
Opened 2023-11-14 15:36 UTC by jemiluv8

## Summary
This is a work in progress towards fulfilling the requirements for the microsoft teams integration

ROADMAP

- [X] Support adding/removing ms teams integration - this just sets up the tenantId and gives our microsoft application access to the tenants ms teams and other related resources
- [ ] Support sending notifications via microsoft teams channels for all alert types - session, log, error.
- [ ] Figure out bot registration issues for tenant
- [ ] Final testing and delivery

## How did you test this change?

- [ ] Visit integrations page
- [ ] Observe a new integration titled, Microsoft Teams
- [ ] Toggle the Microsoft teams integration
- [ ] Follow the redirect to authorize app permission
- [ ] Observe the integration is successfully "synced" with highlight
- [ ] Observe that you are able to "remove" the microsoft teams integration
... more to follow

## Are there any deployment considerations?
New Environment Variables
MICROSOFT_TEAMS_CLIENT_ID
MICROSOFT_TEAMS_CLIENT_SECRET

Above can be obtained by creating a new microsoft applications.
Ensure the application is allowed access to the tenant's ms teams channels as well as ability to send messages to all
ms teams channels.

There will be more since this is very much a work in progress.

## Does this work require review from our design team?
Not yet

fixes #6858 

<img width="687" alt="Screenshot 2023-11-14 at 3 34 45 PM" src="https://github.com/highlight/highlight/assets/119384208/806860f3-a8a3-4d2f-997e-64028cc7a5c1">

2024-01-03 18:29 UTC, jemiluv8 commented on backend/alerts/integrations/microsoft-teams/message_templates.go
> +var ErrorAlertMessageTemplate = []byte(`{
Most messages sent by the ms teams bot use adaptive cards.
Even though they need to be valid json, I treat them like templates.
The "rendered" template must however be valid json.

2024-01-03 18:29 UTC, jemiluv8 commented on backend/alerts/integrations/microsoft-teams/messages_test.go
> +package microsoft_teams
I'm taking a leaf out of the example set by the discord implementation.
This is probably the fastest and most effective way to test the ms teams
bot.

Successfully running this test validates about 60+% of the work for this PR.

2024-01-03 18:29 UTC, jemiluv8 commented on backend/alerts/integrations/microsoft-teams/microsoft_teams.go
> +func GetTeamsChannel(workspace *model.Workspace) ([]*model.MicrosoftTeamsChannel, error) {
I chose to save the ms teams channels on the workspace as a mapping of teamId to list of channels

2024-01-03 18:29 UTC, jemiluv8 commented on backend/alerts/integrations/microsoft-teams/templates_test.go
> +package microsoft_teams
My treatment of adaptive cards can be error prone. 
Tests need to exist of all templates.

2024-01-03 18:29 UTC, jemiluv8 commented on backend/main.go
> +		r.Post(fmt.Sprintf("%s/%s", privateEndpoint, "microsoft-teams/bot"), privateResolver.MicrosoftTeamsBotEndpoint)
An endpoint it needed by the microsoft bot framework when setting up a bot.
This is used by the framework to send messages to the bot.

All request validation is done by the msbotbuilder framework

2024-01-03 18:29 UTC, jemiluv8 commented on backend/private-graph/graph/resolver.go
> +	if err := r.DB.Transaction(func(tx *gorm.DB) error {
We remove the tenant integration and the channels saved on the workspace.
We then remove teams channels to notify on all alerts.

2024-01-03 18:29 UTC, jemiluv8 commented on backend/private-graph/graph/resolver.go
> +	act, err := bot.ParseRequest(ctx, req)
This effectively "validates" and authenticates the request using our client id and secret.
It also extracts the payload into a friendly form that we are able to interact with.

2024-01-03 18:29 UTC, jemiluv8 commented on backend/private-graph/graph/resolver.go
> +			for _, memberRemoved := range act.MembersRemoved {
MS teams bot can be installed in multiple "teams/groups" for the same integration (aka tenantID).
So when the bot is removed, we just remove the channels that had previously been saved
belonging to the team/group removed.

2024-01-03 19:15 UTC, jemiluv8 reviewed
Self Review completed

2024-01-18 02:12 UTC, mayberryzane requested changes
sorry for the delay here! code looks good, just a few small items and will click test tomorrow

2024-01-18 02:12 UTC, mayberryzane commented on frontend/src/pages/Alerts/ErrorAlert/ErrorAlertPage.tsx
> +							console.log('Input', input)
can remove this console.log

2024-01-18 02:12 UTC, mayberryzane commented on frontend/src/pages/Setup/SetupRouter/AlertsSetup.tsx
> +			// TODO: do we have to do same for microsoft_teams platform?
is this comment still relevant?

2024-01-18 10:51 UTC, jemiluv8 commented on backend/alerts/alerts.go
> +		for _, channel := range event.ErrorAlert.DiscordChannelsToNotify {
Correct.

2024-01-18 10:51 UTC, jemiluv8 commented on backend/alerts/alerts.go
> +		bot, err := microsoft_teams.NewMicrosoftTeamsBot(*event.Workspace.DiscordGuildId)
Correct

2024-01-18 10:51 UTC, jemiluv8 commented on frontend/src/pages/Setup/SetupRouter/AlertsSetup.tsx
> +			// TODO: do we have to do same for microsoft_teams platform?
No. Its been removed now.

2024-01-18 10:53 UTC, jemiluv8 commented
I've made changes requested.

2024-01-23 01:59 UTC, mayberryzane commented
Hi @jemiluv8, thank you. I set up the integration locally and it was mostly looking good. I had 2 questions:
1. After integrating with Highlight, would it be possible to retrieve all available Teams channels whenever the alerts page is loaded instead of when the bot is installed? It's a little clunky at the moment because if a bot is added before Highlight is integrated, the alerts UI shows no available channels. Does this also mean we would have to re-install the bot in Teams whenever new channels are added?
2. How can a user delete the bot/app in Teams after it is installed and added to a team? Is there anything we can do to list the team here under "Recently Used" on the "Manage your apps" page?
<img width="811" alt="Screen Shot 2024-01-22 at 5 40 58 PM" src="https://github.com/highlight/highlight/assets/86132398/ad7a39fa-363a-4871-86bd-d2e846e1d9cc">

2024-01-23 11:57 UTC, jemiluv8 commented
> How can a user delete the bot/app in Teams after it is installed and added to a team? 

I'm assuming you want the bot to be uninstalled on all Microsoft teams under the tenant whenever the highlight UI integration is "removed". I have to look into this. I expect there could be an api call that can do this.

At the moment, since we support installing the bot on multiple "teams" under the same "tenant", we remove the teams integration on highlight when the bot is removed and there are no longer other bot installations for the tenant. 

_So when we do a teams integration and install the bot on one "team", uninstalling the bot on the team will also "remove" the highlight integration._

> Is there anything we can do to list the team here under "Recently Used" on the "Manage your apps" page?

I'm not sure I understand. Based on the screenshot below, it seems the team is listed there or I'm missing something.
<img width="722" alt="Screenshot 2024-01-23 at 11 43 31 AM" src="https://github.com/highlight/highlight/assets/119384208/b4ef6a01-6af7-4594-9474-b7c34a3df161">

2024-01-23 18:01 UTC, mayberryzane commented
@jemiluv8 
> Installing the bot before highlight UI integration is a no op because there is no way we can associate the "team" the bot was installed on and the highlight workspace/account. So our "reasonable" constraint is to ensure that the integration is done on highlight UI before the bot is installed.

If the change was made to fetch all available channels instead of updating that channels list, wouldn't this be possible? Whenever a user is on the alerts page, we could fetch all teams available to the bot under the Teams tenant id associated with the Highlight workspace, then fetch all channels in each of those teams. I think for maintainability, it will be a lot easier if we're fetching the channels list whenever the user is on the alerts screen. In most cases, the bot will only be added to one or two teams, and updating an alert is an infrequent action, so if it takes a second or two to load all channels, this is still a better UX than showing an outdated channel list or requiring the bot to be installed. Plus, fetching the channels for each team can be parallelized. Thanks for including all the details in your caveat.

For deleting, maybe I hit some weird bug on my end with the MacOS version of Teams, but it's preventing me from setting up the Highlight integration after disabling it in the Highlight UI because I am unable to uninstall / reinstall the bot. I think if the above change is possible, this won't be an issue. Thank you!

2024-01-23 18:08 UTC, jemiluv8 commented
> @jemiluv8
> 
> > Installing the bot before highlight UI integration is a no op because there is no way we can associate the "team" the bot was installed on and the highlight workspace/account. So our "reasonable" constraint is to ensure that the integration is done on highlight UI before the bot is installed.
> 
> If the change was made to fetch all available channels instead of updating that channels list, wouldn't this be possible? Whenever a user is on the alerts page, we could fetch all teams available to the bot under the Teams tenant id associated with the Highlight workspace, then fetch all channels in each of those teams. I think for maintainability, it will be a lot easier if we're fetching the channels list whenever the user is on the alerts screen. In most cases, the bot will only be added to one or two teams, and updating an alert is an infrequent action, so if it takes a second or two to load all channels, this is still a better UX than showing an outdated channel list or requiring the bot to be installed. Plus, fetching the channels for each team can be parallelized. Thanks for including all the details in your caveat.
> 
> For deleting, maybe I hit some weird bug on my end with the MacOS version of Teams, but it's preventing me from setting up the Highlight integration after disabling it in the Highlight UI because I am unable to uninstall / reinstall the bot. I think if the above change is possible, this won't be an issue. Thank you!

Agreed. Will make sure we always fetch the ms teams channels when on the alerts page. I will also parallelize the api requests.

2024-01-23 18:13 UTC, mayberryzane commented
@jemiluv8 also just pushed a few copy changes and renamed all usages of `MICROSOFT_TEAMS_CLIENT_ID` to `MICROSOFT_TEAMS_BOT_ID` - was there a reason to have separate environment variables here or is ok for them to be the same? My understanding is that these are the same IDs, feel free to revert that if it's an issue

2024-01-23 18:21 UTC, jemiluv8 commented
> @jemiluv8 also just pushed a few copy changes and renamed all usages of `MICROSOFT_TEAMS_CLIENT_ID` to `MICROSOFT_TEAMS_BOT_ID` - was there a reason to have separate environment variables here or is ok for them to be the same? My understanding is that these are the same IDs, feel free to revert that if it's an issue

I've seen, reviewed and agree with the changes. They are the same IDs.

2024-01-24 14:15 UTC, jemiluv8 commented on backend/alerts/integrations/microsoft-teams/microsoft_teams.go
> +func GetMicrosoftTeamsChannelSuggestions(workspace *model.Workspace) ([]*model.MicrosoftTeamsChannel, error) {
This feels overkill and I also return the first error we encounter.
Below is a simpler non-concurrent version I wrote

```go
func GetTeamsChannel(workspace *model.Workspace) ([]*model.MicrosoftTeamsChannel, error) {
	allChannels := []*model.MicrosoftTeamsChannel{}
	teamsGroups := GetMicrosoftTeamsGroupsFromWorkspace(workspace)

	for _, teamGroup := range teamsGroups {
		channels, err := GetMicrosoftTeamsChannels(*workspace.MicrosoftTeamsTenantId, teamGroup)
		if err != nil {
			return nil, err
		}
		allChannels = append(allChannels, channels...)
	}

	return allChannels, nil
}
```
I feel like there is a simpler way to do this but I'm unable to find one at the moment.
You can rewrite this or suggest a "better" way of going about this.

2024-01-24 17:12 UTC, jemiluv8 commented
I've introduced support for fetching the ms teams channels directly from the microsoft graph api.

2024-01-29 17:00 UTC, mayberryzane commented
thanks @jemiluv8 , testing this today

2024-01-29 23:35 UTC, mayberryzane commented
@jemiluv8 just made a couple more changes - I stopped saving the groups with the workspace and instead just save tenant id, then use the `/teams` endpoint to load all teams. Tested a concurrent / non-concurrent version on a teams instance with 6 teams, took 1.6s for the concurrent version and 3.5s for the non-concurrent one so decided to keep it concurrent (changed it to use the errgroup library). For permissions, I think it just needs these:
<img width="1011" alt="Screen Shot 2024-01-29 at 3 34 20 PM" src="https://github.com/highlight/highlight/assets/86132398/ed0de5dc-75ee-4a00-9032-dfd127e1d97a">

Should be good to merge in now, I'll make sure it gets merged in / passes checks. Thanks for all your work here!

2024-01-29 23:35 UTC, mayberryzane approved these changes

2024-01-30 00:59 UTC, jemiluv8 commented
### Just to clarify
The changes look good to me. 

One issue with fetching all teams(under the tenant) and then all channels is that we cannot send to a channel until the bot is installed on the team. At the moment, we don't "default install" the bot on all teams under the tenant.

### This means
So we can setup an alert to be sent to a teams channel that will not receive the message if the bot is not installed on the "team"

### Conclusion
That was the reason I was storing the list of teams the bot was installed on in the workspace. So I only fetch the channels for these teams. Also, when a bot is uninstalled from a team, we remove the team from the list of teams. That fixes the above issue to some extent.

### Options
One thing we could do is to "auto install" the teams bot on all teams in the channel.

2024-01-30 20:51 UTC, mayberryzane commented
@jemiluv8 thanks for the additional context, I just added another check to verify that our app is installed in the team by using [this api](https://learn.microsoft.com/en-us/graph/api/team-list-installedapps?view=graph-rest-1.0&tabs=http). Not great because it's a 2n+1 query, but in testing this took about 2s which should be fine as it's only when loading the alerts page for users with many team. We can look at optimizing in the future if this becomes a user pain point, but it keeps all the state of which teams our bot is installed on on the MS Teams side so there's no issue of keeping our state in sync. Will merge this in today

2024-01-30 23:20 UTC, jemiluv8 commented
Your update works just fine. I think I finally understand our differing “points of view” about “state”

Your preference for not having some state to keep in sync helps avoid a lot of problems 
with managing state even though it may not be the most performant.

At the same time too doing all this exxtra work to sync state over time can lead to bugs that we may have a hard time
keeping track of. The trade-off in this case makes sense because performance is not the priority right now. And the expected
number of users using this feature is “expected to be low”.

I’ll keep this in mind for future work on integrations. Its been cool collaborating on this.

2024-01-31 00:38 UTC, merged

2024-04-27 05:43 UTC, Vadman97 commented
/tip @jemiluv8 200

2024-04-27 05:44 UTC, Vadman97 commented
/tip $200 @jemiluv8