7460 highlight for startups page design edits
highlight/highlight pull request #7461
Opened 2024-01-10 21:09 UTC by Abhishek-More

## Summary

See attached issue

## How did you test this change?

Click-testing

## Are there any deployment considerations?

No

## Does this work require review from our design team?

No

2024-01-12 00:40 UTC, Vadman97 requested changes
don't see the hero images at all on the vercel preview

![Screenshot from 2024-01-11 16-38-01](https://github.com/highlight/highlight/assets/1351531/c56d19af-b87c-4832-8651-9843941e7c89)

2024-01-12 00:40 UTC, Vadman97 commented on highlight.io/pages/startups.tsx
the shirt and mug photo is quite large and seems to take a while to load

2024-01-13 19:54 UTC, jay-khatri approved these changes

2024-01-21 06:18 UTC, Abhishek-More commented on highlight.io/pages/startups.tsx
Compressed the photo to webp, should load faster now. Also I can see the hero image in the screenshot, is there something I am missing?

2024-02-01 23:29 UTC, Vadman97 approved these changes

2024-02-01 23:29 UTC, merged