New Select component in UI package
highlight/highlight pull request #8671
Opened 2024-05-24 16:08 UTC by ccschmitz

## Summary

## How did you test this change?

## Are there any deployment considerations?

## Does this work require review from our design team?

2024-08-07 17:29 UTC, ccschmitz commented on packages/ui/src/components/Button/Button.stories.tsx
> +								iconLeft={<IconSolidCheveronDown />}
Fixed these stories which weren't rendering icons correctly

2024-08-07 17:29 UTC, ccschmitz commented on packages/ui/package.json
> +		"storybook": "^8.2.6",
Some of the Storybook config changes came from running the auto upgrade task from the Storybook CLI.

2024-08-07 20:19 UTC, SpennyNDaJets requested changes
Looking great! Just left a couple comments from click test:

1. On `ErrorAlertPage`, not able to select an option
![Screenshot 2024-08-07 at 4 10 37 PM](https://github.com/user-attachments/assets/bbaeea92-3d43-48fd-9706-2de30debecdf)

2. Also saw it was used on the SessionAlertForm, but wondering if `configuration.canControlThreshold ` should just be cleaned up?

2024-08-07 20:19 UTC, SpennyNDaJets commented on frontend/src/pages/Alerts/LogAlert/LogAlertPage.tsx
Very nitty: but when you change the Alert frequency, the width of the select changes here

2024-08-07 20:19 UTC, SpennyNDaJets commented on frontend/src/pages/WorkspaceTeam/components/AutoJoinForm.tsx
Seeing an error that may be related when trying to access:
- https://preview.highlight.io/w/1/settings
- https://preview.highlight.io/w/1/team

```
TypeError: Cannot read properties of undefined (reading 'length')
```

2024-08-09 03:53 UTC, ccschmitz commented on frontend/src/pages/WorkspaceTeam/components/AutoJoinForm.tsx
Thanks for catching this! Just fixed that up. It was an issue with auto join form.

2024-08-09 03:58 UTC, ccschmitz commented on frontend/src/pages/Alerts/LogAlert/LogAlertPage.tsx
Fixed by setting `span="6"` on each wrapping `Column` - good catch!

2024-08-09 04:00 UTC, ccschmitz commented
> ... wondering if `configuration.canControlThreshold ` should just be cleaned up?

Maybe so, but I might hold off on that in this PR. Will defer to you on that one with the work you're already doing on alerts 😸 

I think everything else is cleaned up, so this is ready for another look! Thanks for the review!

2024-08-09 04:02 UTC, ccschmitz commented on packages/ui/src/components/Form/styles.css.ts
> +		size: 'small',
Noticed the height of form inputs was slightly off from the mocks. All form inputs were supposed to be 28px tall, which this enforces.

2024-08-09 19:08 UTC, SpennyNDaJets approved these changes
Click test and code look good to me!

2024-08-09 19:31 UTC, ccschmitz commented
Thanks for the review on this, @SpennyNDaJets! Apologies that this got so large...

2024-08-13 01:39 UTC, merged