chunk network resources
highlight/highlight pull request #9318
Opened 2024-09-16 17:20 UTC by Vadman97

## Summary

## How did you test this change?

## Are there any deployment considerations?

## Does this work require review from our design team?

2024-09-18 15:05 UTC, SpennyNDaJets approved these changes
Click test looks good to me!

2024-09-18 15:05 UTC, SpennyNDaJets commented on __generated/rr/rrweb/rr.js
Are these changes anticipated?

2024-09-18 15:42 UTC, SpennyNDaJets requested changes
One thing I noticed is that we are still only returning 50 traces? Looks like the pagination is based on `1_000` but the cursor is not respecting that limit

2024-09-18 20:31 UTC, Vadman97 commented on frontend/src/pages/Player/ResourcesContext/ResourcesContext.tsx
> +		limit: 1_000,
yup meant to say 1000

2024-09-18 20:32 UTC, Vadman97 commented on __generated/rr/rrweb/rr.js
unrelated, reverting

2024-09-18 20:39 UTC, Vadman97 commented
> One thing I noticed is that we are still only returning 50 traces? Looks like the pagination is based on `1_000` but the cursor is not respecting that limit -> think we just need to pass it into `getConnection`

thanks for the callout @SpennyNDaJets and for the help with the fix. just updated this!

2024-09-18 20:49 UTC, Vadman97 commented
new testing https://www.loom.com/share/8016f403dd6a4ac08a1a61886c8e187d

2024-09-19 15:11 UTC, SpennyNDaJets approved these changes
LGTM

2024-09-20 00:34 UTC, merged