fix: nextjs sdk proxy configuration
highlight/highlight pull request #9580
Opened 2024-11-03 13:51 UTC by Rutik7066

## Summary

Added a check. If  `/highlight-events` is set in `next.config`  then it will not push default rewrite.

/claim #9042

2024-11-03 22:43 UTC, Vadman97 requested changes
Hi @Rutik7066 , thanks for the PR. However this is not configuring the [HighlightInit](https://github.com/highlight/highlight/blob/main/sdk/highlight-next/src/next-client.tsx) component as described in the ticket.

2024-11-04 04:49 UTC, Rutik7066 commented
@Vadman97 I think I have misunderstood the issue. Can you please explain me in details what exactly we want. I noticed that when we add `/highlight-events` as backendUrl prop it will add localhost as host in Url is this we want to do it in function

2024-11-05 03:24 UTC, Rutik7066 commented
@Vadman97 

> @Vadman97 I think I have misunderstood the issue. Can you please explain me in details what exactly we want. I noticed that when we add `/highlight-events` as backendUrl prop it will add localhost as host in Url is this we want to do it in function

2024-11-08 11:25 UTC, Rutik7066 commented
@Vadman97 wait for your review.

2024-11-18 18:30 UTC, Rutik7066 commented
@Vadman97 if anything needs to be changed please let me know

2024-12-05 11:11 UTC, Rutik7066 commented on sdk/highlight-next/src/util/with-highlight-config.ts
> +			const url = new URL(backendUrl || 'http://localhost:3000');
@Vadman97 we use locahost:3000 for our backend.

2024-12-05 11:11 UTC, Rutik7066 commented
@Vadman97  github action is failling because it is depreciated.
![Screenshot from 2024-12-05 16-41-11](https://github.com/user-attachments/assets/53233324-d696-499a-b6ea-7f1c96d8a419)

2024-12-09 23:52 UTC, Vadman97 requested changes
this is not the right approach. we need to update https://github.com/highlight/highlight/blob/2339697c4ef5d3546e1ae2d2549dd417f2406657/sdk/highlight-next/src/next-client.tsx#L11-L38 to update `backendUrl` when the `/highlight-events` route is set up

2024-12-09 23:52 UTC, Vadman97 commented on git
please remove this

2024-12-10 17:44 UTC, closed without merging

2024-12-10 17:49 UTC, Rutik7066 commented
@Vadman97 While rebasing the PR, I accidentally closed it. Now, GitHub does not show an option to reopen it, so I will open a new PR.